org.gradle.jvmargs=-Xmx2G
org.gradle.parallel=true
org.gradle.configuration-cache=false

minecraft_version=1.21.11
yarn_mappings=1.21.11+build.4
loader_version=0.18.6
loom_version=1.15.5

mod_version=0.2.0
maven_group=dev.vanta
archives_base_name=vanta

versioning_scheme=semver
release_tag_format=v{mod_version}-mc{minecraft_version}

fabric_api_version=0.141.3+1.21.11
